export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR',
    INFO: 'ALERT_INFO',
    WARN: 'ALERT_WARN'
};

export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',

    UPDATE_PROFILE_PIC_REQUEST: 'UPDATE_PROFILE_PIC_REQUEST',
    UPDATE_PROFILE_PIC_SUCCESS: 'UPDATE_PROFILE_PIC_SUCCESS',
    UPDATE_PROFILE_PIC_FAILURE: 'UPDATE_PROFILE_PIC_FAILURE',

    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',

    CHECK_CURRENT_PASS_REQUEST: 'CHECK_CURRENT_PASS_REQUEST',
    CHECK_CURRENT_PASS_SUCCESS: 'CHECK_CURRENT_PASS_SUCCESS',
    CHECK_CURRENT_PASS_FAILURE: 'CHECK_CURRENT_PASS_FAILURE',
    CHECK_CURRENT_PASS_CLEAR: 'CHECK_CURRENT_PASS_CLEAR',

    UPDATE_PASSWORD_REQUEST: 'UPDATE_PASSWORD_REQUEST',
    UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_FAILURE: 'UPDATE_PASSWORD_FAILURE',
    
    UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',
};

export const membershipConstants ={    
    GET_MEMBERSHIP_PLAN_REQUEST: 'GET_MEMBERSHIP_PLAN_REQUEST',
    GET_MEMBERSHIP_PLAN_SUCCESS: 'GET_MEMBERSHIP_PLAN_SUCCESS',
    GET_MEMBERSHIP_PLAN_FAILURE: 'GET_MEMBERSHIP_PLAN_FAILURE',
};

export const audioConstants = {    
    GET_CAT_REQUEST: 'GET_CAT_REQUEST',
    GET_CAT_SUCCESS: 'GET_CAT_SUCCESS',
    GET_CAT_FAILURE: 'GET_CAT_FAILURE',

    GET_TYPE_REQUEST: 'GET_TYPE_REQUEST',
    GET_TYPE_SUCCESS: 'GET_TYPE_SUCCESS',
    GET_TYPE_FAILURE: 'GET_TYPE_FAILURE',

    GET_ALBUM_REQUEST: 'GET_ALBUM_REQUEST',
    GET_ALBUM_SUCCESS: 'GET_ALBUM_SUCCESS',
    GET_ALBUM_FAILURE: 'GET_ALBUM_FAILURE',

    GET_CAT_AUDIO_REQUEST: 'GET_CAT_AUDIO_REQUEST',
    GET_CAT_AUDIO_SUCCESS: 'GET_CAT_AUDIO_SUCCESS',
    GET_CAT_AUDIO_FAILURE: 'GET_CAT_AUDIO_FAILURE',
};

export const videoConstants = {    
    GET_CAT_REQUEST: 'GET_CAT_REQUEST',
    GET_CAT_SUCCESS: 'GET_CAT_SUCCESS',
    GET_CAT_FAILURE: 'GET_CAT_FAILURE',

    GET_TYPE_REQUEST: 'GET_TYPE_REQUEST',
    GET_TYPE_SUCCESS: 'GET_TYPE_SUCCESS',
    GET_TYPE_FAILURE: 'GET_TYPE_FAILURE',

    GET_ALBUM_REQUEST: 'GET_ALBUM_REQUEST',
    GET_ALBUM_SUCCESS: 'GET_ALBUM_SUCCESS',
    GET_ALBUM_FAILURE: 'GET_ALBUM_FAILURE',

    GET_CAT_VIDEO_REQUEST: 'GET_CAT_VIDEO_REQUEST',
    GET_CAT_VIDEO_SUCCESS: 'GET_CAT_VIDEO_SUCCESS',
    GET_CAT_VIDEO_FAILURE: 'GET_CAT_VIDEO_FAILURE',
};

export const searchConstants ={    
    FETCH_SEARCH_ACTION_BEGIN: 'FETCH_SEARCH_ACTION_BEGIN',
    FETCH_SEARCH_ACTION_SUCCESS:'FETCH_SEARCH_ACTION_SUCCESS',
    FETCH_SEARCH_ACTION_FAILED:'FETCH_SEARCH_ACTION_FAILED'
};

export const playerConstants ={    
    PLAYER_START: 'PLAYER_START',
    PLAYER_PLAYING:'PLAYER_PLAYING',
    PLAYER_PAUSE:'PLAYER_PAUSE',
    PLAYER_CLEAR:'PLAYER_CLEAR'
};